version: '3'

services:
  ### WEB ###################################################
  web:
    image: nginx:latest
    volumes:
    - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - ${APP_WEB_PORT}:80
    links:
    - php
    - composer
  ### PHP ###################################################
  php:
    build: ./php
    volumes:
    - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    links:
    - mysql
  ### MYSQL ###################################################
  mysql:
    image: mysql:latest
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
    volumes:
    - ${DB_MYSQL_PATH_HOST}:/var/lib/mysql
    ports:
    - ${DB_MYSQL_PORT}:3306
    command:
      --default-authentication-plugin=mysql_native_password
  ### COMPOSER ###################################################
  composer:
    image: composer:latest
    restart: always
    volumes:
    - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: ["install ", "dump-autoload --optimize"]
